spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/carddb
  kafka:
    bootstrap-servers: card-status-kafka-1:29092,card-status-kafka-2:29092,card-status-kafka-3:29092

external:
  card-status:
    base-url: http://card-status-mock:8080
